# Generated by Django 5.2.3 on 2025-07-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_post_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagem',
            field=models.ImageField(blank=True, default='', null=True, upload_to='imagens/'),
        ),
    ]
